apiVersion: v1
kind: Service
metadata:
  name: simple-ride-tracking
  labels:
    app: simple-ride-tracking
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: simple-ride-tracking

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-ride-tracking
    version: v1
  name: simple-ride-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-ride-tracking
      version: v1
  template:
    metadata:
      labels:
        app: simple-ride-tracking
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: secretvolume
          secret:
            secretName: datasource
      containers:
        - name: simple-ride-tracking
          image: demo/simple-ride-tracking:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: secretvolume
              mountPath: /stuff/secrets
              readOnly: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "1000m" # 1 core
            limits:
              memory: "300Mi"
              cpu: "1500m"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 10
          securityContext:
            privileged: false